apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: spoke-0
  namespace: spoke-0
spec:
  clusterRef:
    name: spoke-0
    namespace: spoke-0
  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9hb6iTZJypEmzg4IZ767ze60UGhBWnjPXhovWVB7uKputdLzZhmlo36ifkXr/DTk8NGm47r6kXmz9NAF0pDHa5jX6yJFnhS4z5NY/mzsUX41gwiqBKYHgdp/KE1ylE8mbNon5ZpaaGvb876myjjPjPwWsD8hvXZirA5Q8TfDb/Pvgy1dhVH/uN05Ip1vVsp+bFGMPUJVWVUy/Eby5xW6OJv+FBOQq4nu6tslDZlHYXX2TSGrlW4x0i/oQMpKu/Y8ygAdjWqmAy6UBcho1nNWy15cp0jI5Fhjze171vSWZLAqJY+eFcL2kt/09RnY+MXyY/tIf+qNMyBE2Qltigah'
  agentLabels:
    bla: "aaa"
  pullSecretRef:
    name: spoke-0-pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      nmstate_config_cluster_name: spoke-0
