---
apiVersion: v1
data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
kind: Secret
metadata:
    name: spoke-worker-0-1-bmc-secret
    namespace: spoke-0
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
    name: spoke-worker-0-1-bmh
    namespace: spoke-0
    annotations:
      inspect.metal3.io: disabled
      bmac.agent-install.openshift.io/hostname: "spoke-worker-0-1"
      bmac.agent-install.openshift.io/role: "worker"
    labels:
      infraenvs.agent-install.openshift.io: "spoke-0"
spec:
    bmc:
      address: redfish-virtualmedia+https://192.168.128.1:8000/redfish/v1/Systems/40a84700-e9d3-4ccd-bd78-dd0af72207f5
      credentialsName: spoke-worker-0-1-bmc-secret
      disableCertificateVerification: true
    bootMACAddress: 52:54:00:b6:a6:9a
    automatedCleaningMode: disabled
    online: true